language: python
python:
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "nightly"
install:
  - pip3 install mypy
  - git clone -b maketrans-strstr https://github.com/jesopo/typeshed.git jesopo-typeshed
script:
  - pip3 freeze
  - mypy scpl --custom-typeshed jesopo-typeshed
  - python3 -m unittest test
